# Stage 1: Build
FROM node:22-alpine AS build

WORKDIR /garrax
COPY package*.json ./

RUN npm ci --only=production

COPY . .

RUN yarn build

# Stage 2: Run
FROM node:22-alpine

RUN yarn add pm2 -g

WORKDIR /garrax
COPY --from=build /garrax/node_modules ./node_modules
COPY --from=build /garrax .

ENV NODE_ENV=production 
# ENV PORT=3003

# EXPOSE 3003
CMD ["pm2", "start"]