import type { Metadata } from "next";

import "./globals.css";

export const metadata: Metadata = {
    title: "GARAX",
    description: "Generated by create next app"
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    // if (process.env.NODE_ENV === "development") {
    //   setupLocatorUI();
    // }

    return (
        <>{children}</>
    );
}
