'use client';
// import type { Metadata } from "next";
import localFont from "next/font/local";
import { Provider } from "react-redux";
import { store } from '../stores/index';
import "./globals.css";

// export const metadata: Metadata = {
//     title: "GARAX",
//     description: "Generated by create next app"
// };

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    // if (process.env.NODE_ENV === "development") {
    //   setupLocatorUI();
    // }

    return (
        <html lang="en" className="scroll-smooth md:scroll-auto scrollbar">
            <Provider store={store}>
                <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                    {children}
                </body>
            </Provider>
        </html>
    );
}
